//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleLibrary1.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDY
    {
        public int STUDY_ID { get; set; }
        public Nullable<decimal> SELF_STUDY_HOURS_PER_WEEK { get; set; }
        public Nullable<System.DateTime> SELECTED_DATE { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<decimal> HOURS_STUDIED { get; set; }
        public Nullable<decimal> STUDY_HOURS_REMAINDING { get; set; }
        public Nullable<int> CURRENT_WEEK { get; set; }
        public string MODULE_CODE { get; set; }
        public string STUDENT_USERNAME { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
